# Generated by Django 5.0 on 2024-06-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tshirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Photo', models.ImageField(upload_to='')),
                ('Article', models.IntegerField()),
                ('Size', models.CharField(max_length=5)),
                ('Description', models.TextField()),
                ('Price', models.IntegerField()),
                ('Reserve_1', models.TextField()),
                ('Reserve_2', models.TextField()),
                ('Photo_reserve', models.ImageField(upload_to='')),
            ],
        ),
    ]
