# Generated by Django 5.0.6 on 2024-07-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SG_app_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirt',
            name='Size',
        ),
        migrations.AddField(
            model_name='tshirt',
            name='Size_L',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='Size_M',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='Size_S',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='Size_XL',
            field=models.CharField(default='0', max_length=5),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='Photo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
